### ISSUE TITLE
Board is as "not programmed" after update

### ISSUE THREAD

**Issue by PsySc0rpi0n** [MicrochipTech/AVR-IoT-WG-Sensor-Node#4]
Hello.
I'm a new user to this board and I tried to update the board with this firmware v1.0.3.
After I copy and paste the .hex file onto my board, all LEDS go OFF and I cannot make it work again with the default IoT Demo code that updates Google Cloud with the Light and Temp sensor values.

The only way I can get it to work again is to download the default firmware again from Microchip website and upload it onto the board, follow the CLICKME.HTM site and use the newly generated WIFI.CFG. And this procedure doesn't work every time I do it! I have to repeat it several times until the board finally reconnects to my home wireless again.

This file from Github is, apparently, just an update for a specific component of this board and the file I have downloaded from Microchip site, if I'm not mistaken, is the default firmware that the board comes with.
So, there are 2 files:
AVR_IOT_MCC_FinalRelease.X.production.hex ----> downloaded from Microchip website
AVR-IoT_WG_Sensor_Node_v1_0_3.hex ------------> downloaded from Github

I think the order that both files are uploaded might have some relevance here as if I upload AVR_IOT_MCC_FinalRelease.X.production.hex first, the board just won't connect to my home WiFi (red led steady ON), not even after several tries of using the WIFI.CFG generated file. If I upload AVR-IoT_WG_Sensor_Node_v1_0_3.hex file first, all leds are OFF, meaning the board is not even programmed!

Edited:
Detailed info:
KIT-INFO.TXT content
Firmware:       01.05.0142 (hex)
Kit:            AVR-IoT WG                                                  
Serial:         ATML3203081800008269
Device:         ATmega4808          

Cutecom commands output:
version      --> v1.0
cli_version --> v2.0
device       --> 0123FBB41C8A74AFFE

I'm using:
Debian 9.6
Linux Kernel - 4.18.0-0.bpo.3-amd64
MPLAB X IDE 5.10
XC8 v2.00

Thanks
PsySc0rpi0n

**Comment by luciodj** [comment]
Hi and Happy New Year!
I have double-checked the download procedure and verified that version 1.0.3 is working well as posted (on OSX, Windows and Linux-Ubuntu). It is possible that you have not downloaded the .hex file but the full .zip or saved a link to the github page to the Curiosity drive.  
I would recommend that you perform the download and unzip on your local drive first, then make sure to drag and drop only the .hex file (v1.0.3). 
To clarify this for all users I have edited the readme file and renamed the previous fw version .hex file for consistency. (This repository contains only valid fw images for the AVR)
If you could verify that you are now capable of upgrading correctly to  the latest version (you can use the command line interface with  the "version"  command using any terminal program) I would be happy to close this issue. 
Best
    Lucio

**Comment by PsySc0rpi0n** [comment]
I'm sorry for late feedback. I still haven't had the chance to test it again. I'll do it maybe today and maybe I'll record a video so that you guys can check if my procedure is correct or not.

Thank you
Psy

**Comment by rranslam** [comment]
# Related Issue Adventures

I had a similar experience.  I ended up copying BOTH hex files AND the generated `WIFI.CFG` file into the device AND using a different SSID with a passphrase that DID NOT have a `$` in the name. 

Prior to performing the update, the device was only showing the red led even though status file showed "ready".

The update completed and it's now working.  BUT I almost tossed it as it seemed as if it was _bricked_.  Even the red led was not coming on when using only the "103.hex" file.  

The Initial setup and access from Linux wasn't taking, but that was (in retrospec) probably due to only copying the single latest Hex file on the device and *not* including a `WIFI.CFG` (with a different SSID and wifi passcode) at the same time.  No mater, what worked for me was copying BOTH files the `WIFI.CFG` 

## pluging in...

Not auto mounting.  Ok so what is there? 

```
$ dmesg
...
[30699.224378] usb 2-1.8: new full-speed USB device number 5 using ehci-pci
[30699.319184] usb 2-1.8: New USB device found, idVendor=03eb, idProduct=2175
[30699.319191] usb 2-1.8: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[30699.319197] usb 2-1.8: Product: nEDBG CMSIS-DAP
[30699.319203] usb 2-1.8: Manufacturer: Microchip Technology Incorporated
[30699.319207] usb 2-1.8: SerialNumber: ATML3203081800007169
[30699.321654] hid-generic 0003:03EB:2175.000A: hiddev0,hidraw3: USB HID v1.11 Device [Microchip Technology Incorporated nEDBG CMSIS-DAP] on usb-0000:00:1d.0-1.8/input0
[30699.393903] usb-storage 2-1.8:1.4: USB Mass Storage device detected
[30699.393976] scsi host6: usb-storage 2-1.8:1.4
[30699.394072] usbcore: registered new interface driver usb-storage
[30699.397940] cdc_acm 2-1.8:1.1: ttyACM0: USB ACM device
[30699.398265] usbcore: registered new interface driver cdc_acm
[30699.398266] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters
[30699.412806] usbcore: registered new interface driver uas
[30700.393661] scsi 6:0:0:0: Direct-Access     MCHP     Curiosity Nano   1.00 PQ: 0 ANSI: 3
[30700.394600] sd 6:0:0:0: Attached scsi generic sg2 type 0
[30700.395231] sd 6:0:0:0: [sdc] 4096 512-byte logical blocks: (2.10 MB/2.00 MiB)
[30700.396319] sd 6:0:0:0: [sdc] Write Protect is off
[30700.396326] sd 6:0:0:0: [sdc] Mode Sense: 0f 00 00 00
[30700.398942] sd 6:0:0:0: [sdc] No Caching mode page found
[30700.398951] sd 6:0:0:0: [sdc] Assuming drive cache: write through
[30700.407522]  sdc:
[30700.411729] sd 6:0:0:0: [sdc] Attached SCSI removable disk
```
Ok so its a storage device `[sdc]`, a serial port `ttyACM0` ?

```
$ sudo fdisk /dev/sdc -l
Disk /dev/sdc: 2 MiB, 2097152 bytes, 4096 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000
```

Ok so let's mount it
```
$ sudo mkdir /media/avr-iot-wg
$ sudo mkdir -t vfat /dev/sdc/ /media/avr-iot-wg
$ mount | grep sdc
/dev/sdc on /media/avr-iot-wg type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
```
What's there?
```
$ ls /media/avr-iot-wg/
AUTORUN.ICO  AUTORUN.INF  CLICK-ME.HTM  KIT-INFO.HTM  KIT-INFO.TXT  PUBKEY.TXT  STATUS.TXT
```

Ok now open the files..

file KIT_INFO.TXT
```
Firmware:       01.04.013C (hex)
Kit:            AVR-IoT WG                                                  
Serial:         ATML3203081800007169
Device:         ATmega4808
```
STATUS.TXT
```
Ready.
```
Open click-me in a browser

Enter your wifi info,  Click Download Configuration
It creates the WIFI.cfg file and ask you to "drag and drop"  Just save it and then cp to the device

```
sudo cp WIFI.CFG /media/avr-iot-wg/
```
Reset the board

**NOTE:**  _this is where I need to change the passphase from `*****$*******`  to remove the `$` as it seems as if the command processor doesn't handle the a '$' in the passphrase._

## Firmware update

Copy BOTH .hex files AND the `WIFI.CFG` file to the drive, then umount and re-plug the device.

The Blue LED and Green LED are on and the yellow LED pulses.
Remount and look at the `STATS.TXT` file  It's `Ready`

Browse to the cloud, it's there and working.

https://avr-iot.com/device/0123BFC18FA06C32FE

Good to go

**Comment by luciodj** [comment]
Thanks rranslam, that's a nicely detailed recount!
I noticed in your report (and others I am receiving) that there is a misconception about the meaning of the _status.txt_ pseudo-file and in general the other pseudo-files reported by the DEBUG chip. So I will try to explain it here and probably copy it over into the wiki later.... (probably a better idea).

The message contained in the _status.txt_ file  is referring only to the very latest operation performed by the DEBUG chip, NOT the AVR  and certainly NOT the WINC module (successful or otherwise) connection.
So if the last operation was a reprogramming of the AVR microcontroller (following a .hex file drag & drop), a "Ready" will confirm a successful decoding of the hex file and programming of the AVR chip.
If the last operation was a WIFI-credentials update, (WIFI.CFG or WIFI.TXT), this means that the file received was correctly interpreted (by the DEBUG chip) and _passed along_ to the AVR for updating of the WIFI-credentials. This still tells you nothing about the following successful or otherwise completion of the operation performed by the AVR (which receives the file contents and requests the WINC module to attempt to establish connection to a new AP with a new password.
The WIFI.CFG contents could still be rejected by the AVR command line parser (CLI.C) and or the WINC might fail to connect to the requested SSID/psw.

To diagnose these cases, I'd recommend that you have a terminal program connected to the virtual serial port of the board. You will be able then, to observe the WIFI-credentials update "live" and see the AVR parser (CLI.C) responses. This will give you the ultimate insight if something is going wrong (SSID and/or passwords too long, or parameters missing, ...)

The  BLUE  LED eventually will tell you if a connection was established with the requested AP (SSID/psw correct). Keep in mind that the WIFI handshake can take anywere from a few hundred of milliseconds up to and in excess of 5 seconds. So, don't expect an immediate gratification. 

Also a BLUE LED means only that a successful connection with your local router has been achieved. 
Many things can still go wrong... (MQTT ports blocked, NTP ports blocked, connection timeouts, SERVER authentication failure...) 
Only when you see the GREEN LED on, you know you made it to the Cloud!
The Yellow LED blinking is your ultimate sign that data packets are being sent...

Hope this helps...

**Comment by luciodj** [comment]
About the need to download the WIFI credentials again each time the board firmware is updated:
It must be noted that the current fw implementation (up to and including 1.0.3) provides for the WIFI-credentials (to your local router) to be stored by the AVR in its internal EEPROM. 
When the device is re-programmed by the DEBUG chip (drag and drop or via MPLAB X/ STUDIO), the device is first **bulk erased**, hence all the EEPROM contents are lost!
NOTE: If you are using MPLAB X or STUDIO you can find settings that will ensure the EEPROM is NOT erased automatically when reprogramming the device, but if you stick to the basic drag'n drop functionality that cannot be avoided and you will have to redo the WIFI-credentials update each time. 

We have received complaints about some users worrying about exposing the SSID/psw in the AVR EEPROM (protected but definitely not as secure as the ECC608!). 
This is an implementation detail that we are planning to change  in the upcoming firmware revisions although this might force us to change a bit the "classroom default"  activation procedure. It's convenience vs. security once more!

Stay tuned...

**Comment by PsySc0rpi0n** [comment]
I'm sorry to come back here but I still can't program the board and conenct to my WiFi using .hex and WIFI.cfg files and drag&drop.

I'm absolutely sure I'm dragging & dropping only the .hex file and the WIFI.cfg file. No zip files.
Also, when I drag the .hex file, I think the board is programmed because all 3 pins blink one followd by another 2 times. But then I can't make it to connect to my router.

The steps I do are:
Connect the board to laptop
Drag & Drop .hex file into CURIOSITY device
wait until 4 leds flash twice (like: Blue, Green Yellow, red, Blue Green, Yellow, red)
Disconnect and connect again the board. Leds blink again in the same way.
Drag & Drop the WIFI.cfg file into CURIOSITY device
Wait to see if it connects. It doesn't connect because red led turns on
Disconnect and reconnect the device to the laptop. 4 leds blink twice and then red led turns on.

I can connect to it via minicom and I can see the version of each firmware I try to install there and it's correct. STATUS file says ready meaning that the last action was OK (I presume last action as being the device programmed with the .hex file, not sure if the WIFI.cfg is supposed to change that state or not too).

I also tried to send the command to connect to WiFi via minicom and it says OK but it changes nothing because red led stays on.
The command is:
wifi MyWirelessName,MyPassword,2

PS:
Actually the only one I can make it work is this hex:
AVR-IoT_WG_Sensor_Node_v1_1_0.hex

**Comment by luciodj** [comment]
Perhaps a live debugging session on skype (or other platform of your choice) could help. 
We are in the same time zone, just drop me a direct email to lucio.dijasio@microchip.com
Best
